setwd("C:/Users/wdu/Downloads/exdata-data-household_power_consumption")
data <- read.table('household_power_consumption.txt',sep = ";",head = TRUE)
newdata <- data[data$Date %in% c(as.Date('2007-02-01'),as.Date('2007-02-02')),]
plot4data <- newdata
plot4data$Data_Time = paste(plot4data$Date,plot4data$Time,sep=' ')
plot4data$Data_Time <- strptime(plot4data$Data_Time,format='%Y-%m-%d %H:%M:%S')
plot4data$Sub_metering_1 <- as.numeric(as.character(plot4data$Sub_metering_1))
plot4data$Sub_metering_2 <- as.numeric(as.character(plot4data$Sub_metering_2))
plot4data$Sub_metering_3 <- as.numeric(as.character(plot4data$Sub_metering_3))
plot4data$Global_active_power <- as.numeric(as.character(plot4data$Global_active_power))
plot4data$Global_reactive_power <- as.numeric(as.character(plot4data$Global_reactive_power))
plot4data$Voltage<-as.numeric(as.character(plot4data$Voltage))
par(mfrow=c(2,2))
plot(plot4data$Data_Time,plot4data$Global_active_power,type="l",xlab='',ylab='Global Active Power(kilowatts)')
plot(plot4data$Data_Time,plot4data$Voltage,type="l",xlab='datetime',ylab='Voltage')
plot(plot4data$Data_Time,plot4data$Sub_metering_1,type='l',xlab='',ylab='Energy sub metering')
points(plot4data$Data_Time,plot4data$Sub_metering_2,type = 'l',col='red')
points(plot4data$Data_Time,plot4data$Sub_metering_3,type = 'l',col='blue')
legend('topright',legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col = c("black","red","blue"),lty = 1,pt.cex=1,cex=0.5)
plot(plot4data$Data_Time,plot4data$Global_reactive_power,type="l",xlab='datetime',ylab='Global_reactive_power')